spring:
  application:
    name: Ledger Pal
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: user
    password: ledger
  jpa:
    properties:
      hibernate.default_schema: ledger
      hibernate.format_sql: true
jwt:
  secret: 61ffQudEJbPqUOC9PZT1yRgi21t6yvVEhjmH/Chw8DCPTHuw2IrKvR0kqtl56Yi6NSco7XN44Mc8c9EY55jnSA==